// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Entities;

public partial class tbDepartamentos
{
    public int depa_Id { get; set; }

    public string depa_Codigo { get; set; }

    public string depa_Nombre { get; set; }

    public int depa_UsuaCreacion { get; set; }

    public DateTime depa_FechaCreacion { get; set; }

    public int? depa_UsuaModificacion { get; set; }

    public DateTime? depa_FechaModificacion { get; set; }

    public bool? depa_Estado { get; set; }

    public virtual tbUsuarios depa_UsuaCreacionNavigation { get; set; }

    public virtual tbUsuarios depa_UsuaModificacionNavigation { get; set; }

    public virtual ICollection<tbMunicipios> tbMunicipios { get; set; } = new List<tbMunicipios>();
}