// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Entities;

public partial class tbPantallas
{
    public int pant_Id { get; set; }

    public string pant_Nombre { get; set; }

    public string pant_URL { get; set; }

    public virtual ICollection<tbRolesXPantallas> tbRolesXPantallas { get; set; } = new List<tbRolesXPantallas>();
}