// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Entities;

public partial class tbRoles
{
    public int role_Id { get; set; }

    public string role_Nombre { get; set; }

    public bool? role_Estado { get; set; }

    public int role_UsuaCreacion { get; set; }

    public DateTime role_FechaCreacion { get; set; }

    public int? role_UsuaModificacion { get; set; }

    public DateTime? role_FechaModificacion { get; set; }

    public virtual tbUsuarios role_UsuaCreacionNavigation { get; set; }

    public virtual tbUsuarios role_UsuaModificacionNavigation { get; set; }

    public virtual ICollection<tbRolesXPantallas> tbRolesXPantallas { get; set; } = new List<tbRolesXPantallas>();

    public virtual ICollection<tbUsuarios> tbUsuarios { get; set; } = new List<tbUsuarios>();
}