// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Entities;

public partial class tbSucursalesXColaboradores
{
    public int suco_Id { get; set; }

    public int sucu_Id { get; set; }

    public int cola_Id { get; set; }

    public decimal suco_DistanciaKm { get; set; }

    public int suco_UsuaCreacion { get; set; }

    public DateTime suco_FechaCreacion { get; set; }

    public virtual tbColaboradores cola { get; set; }

    public virtual tbUsuarios suco_UsuaCreacionNavigation { get; set; }

    public virtual tbSucursales sucu { get; set; }
}