// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Entities;

public partial class tbSucursales
{
    public int sucu_Id { get; set; }

    public string sucu_Nombre { get; set; }

    public string sucu_Direccion { get; set; }

    public int muni_Id { get; set; }

    public bool? sucu_Estado { get; set; }

    public int sucu_UsuaCreacion { get; set; }

    public DateTime sucu_FechaCreacion { get; set; }

    public int? sucu_UsuaModificacion { get; set; }

    public DateTime? sucu_FechaModificacion { get; set; }

    public virtual tbMunicipios muni { get; set; }

    public virtual tbUsuarios sucu_UsuaCreacionNavigation { get; set; }

    public virtual tbUsuarios sucu_UsuaModificacionNavigation { get; set; }

    public virtual ICollection<tbSucursalesXColaboradores> tbSucursalesXColaboradores { get; set; } = new List<tbSucursalesXColaboradores>();

    public virtual ICollection<tbViajes> tbViajes { get; set; } = new List<tbViajes>();
}