// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Entities;

public partial class tbTransportistas
{
    public int tran_Id { get; set; }

    public string tran_Nombres { get; set; }

    public string tran_Apellidos { get; set; }

    public string tran_Identidad { get; set; }

    public decimal tran_TarifaKm { get; set; }

    public DateTime tran_FechaNacimiento { get; set; }

    public string tran_Sexo { get; set; }

    public bool? tran_Estado { get; set; }

    public int tran_UsuaCreacion { get; set; }

    public DateTime tran_FechaCreacion { get; set; }

    public int? tran_UsuaModificacion { get; set; }

    public DateTime? tran_FechaModificacion { get; set; }

    public virtual ICollection<tbViajes> tbViajes { get; set; } = new List<tbViajes>();

    public virtual tbUsuarios tran_UsuaCreacionNavigation { get; set; }

    public virtual tbUsuarios tran_UsuaModificacionNavigation { get; set; }
}