// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Entities;

public partial class tbViajesDetalles
{
    public int vide_Id { get; set; }

    public int viaj_Id { get; set; }

    public int cola_Id { get; set; }

    public bool? vide_Estado { get; set; }

    public int vide_UsuaCreacion { get; set; }

    public DateTime vide_FechaCreacion { get; set; }

    public int? vide_UsuaModificacion { get; set; }

    public DateTime? vide_FechaModificacion { get; set; }

    public virtual tbColaboradores cola { get; set; }

    public virtual tbViajes viaj { get; set; }

    public virtual tbUsuarios vide_UsuaCreacionNavigation { get; set; }

    public virtual tbUsuarios vide_UsuaModificacionNavigation { get; set; }
}